init
brstu/GIIS-2023 pull request #1
Opened 2023-09-15 14:36 UTC by hrshprivate

task_01 doroshuk

2023-09-18 19:39 UTC, hrshprivate commented
Не прошел проверку с единственным пуллом?)))

2023-09-18 21:43 UTC, hrshprivate commented
Мб проблема в отсутствии расширения js
file_extensions: 'h, hpp, c, cpp, cc, java, py, cs, js', можно сделать коммит в master ветку, тогда должен пройти

2023-09-19 16:02 UTC, akayohonda approved these changes

2023-09-19 16:20 UTC, akayohonda approved these changes

2023-09-19 16:20 UTC, akayohonda approved these changes
good

2023-09-21 12:32 UTC, NogameNo-life requested changes

2023-09-22 08:07 UTC, NogameNo-life approved these changes

2023-09-22 08:39 UTC, akayohonda approved these changes

2023-09-25 05:33 UTC, merged