[task_03] Add task 03
brstu/GIIS-2023 pull request #10
Opened 2023-10-08 15:07 UTC by SergeyGalanin

2023-10-08 18:28 UTC, ElXoce approved these changes
Best clinic site in the history of our country

2023-10-09 10:57 UTC, ElGansoDorado approved these changes

2023-10-17 19:28 UTC, NogameNo-life requested changes
Конфликты надо разрешить

2023-10-25 22:57 UTC, NogameNo-life approved these changes

2023-10-25 23:01 UTC, merged