[task_04_05] Add_task_04_05
brstu/GIIS-2023 pull request #24
Opened 2023-11-01 13:48 UTC by SergeyGalanin

2023-11-01 13:56 UTC, ElXoce approved these changes
геймдизайнер не по годам.

2023-11-12 21:21 UTC, ElGansoDorado approved these changes

2023-11-15 07:31 UTC, NogameNo-life requested changes
1316 файлов перебор, ветку не обновили, где есть godot в .gitignore.

2023-11-19 14:21 UTC, NogameNo-life approved these changes

2023-11-19 14:21 UTC, merged