[task_06] Doroshuk
brstu/GIIS-2023 pull request #31
Opened 2023-11-17 17:06 UTC by hrshprivate

2023-11-17 19:09 UTC, akayohonda commented
very good

2023-11-17 19:10 UTC, akayohonda approved these changes
very good

2023-11-19 14:00 UTC, NogameNo-life reviewed
В safari почему то не работает, но я могу и так принять..

2023-11-19 14:00 UTC, NogameNo-life approved these changes

2023-11-19 14:23 UTC, NogameNo-life requested changes

2023-11-19 14:23 UTC, NogameNo-life commented on README.md
> +|1 |Дорошук Евгений|[hrshprivate](https://github.com/hrshprivate)|200103|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check
```suggestion
|1 |Дорошук Евгений|[hrshprivate](https://github.com/hrshprivate)|[200103](./trunk/ii200103/)|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:||||
```

2023-11-21 07:24 UTC, NogameNo-life approved these changes

2023-11-21 07:24 UTC, merged