[task_01]add task_01
brstu/GIIS-2023 pull request #5
Opened 2023-09-26 13:38 UTC by ElXoce

2023-09-26 18:26 UTC, SergeyGalanin approved these changes
:hear_no_evil::speak_no_evil::see_no_evil::trollface:

2023-09-27 05:11 UTC, NogameNo-life requested changes

2023-09-27 05:11 UTC, NogameNo-life commented on trunk/ii200111/task_01/README.md
> +![nonlin](doc/pictures/korablik.png)
```suggestion
![nonlin](doc/pictures/korablik.jpg)
```

2023-09-27 06:55 UTC, SergeyGalanin commented
:bulb::bulb::bulb:

2023-09-27 06:56 UTC, SergeyGalanin commented on trunk/ii200111/task_01/README.md
> +![nonlin](doc/pictures/korablik.png)
:trophy:

2023-09-27 06:58 UTC, SergeyGalanin commented
:six_pointed_star:

2023-09-27 09:03 UTC, NogameNo-life approved these changes

2023-09-28 16:28 UTC, ElGansoDorado approved these changes
💪

2023-09-29 12:58 UTC, NogameNo-life requested changes

2023-09-29 12:58 UTC, NogameNo-life commented on README.md
> +|10|Федорук Александр|[Zhirbolostt](https://github.com/Zhirbolostt)||||||||||||
Отметьте себе task_00 и task_01

2023-09-29 15:46 UTC, ElXoce commented on README.md
> +|10|Федорук Александр|[Zhirbolostt](https://github.com/Zhirbolostt)||||||||||||
Это не я. Я второй в списке. После разрешения конфликта эта строчка как-то криво сохранилась. Может где-то был пробел или что-то такое. На гите видно, что строки одинаковые.

2023-10-02 10:58 UTC, merged