Add_task_01
brstu/GIIS-2023 pull request #7
Opened 2023-09-26 14:22 UTC by ElGansoDorado

2023-09-28 05:06 UTC, NogameNo-life requested changes

2023-09-28 05:06 UTC, NogameNo-life commented on trunk/ii200115/task_01/README.md
> +    ![nonlin](doc/pictures/laba.png)
```suggestion
    ![nonlin](doc/pictures/laba.jpg)
```

2023-09-28 08:37 UTC, ElXoce reviewed
🙏✡✡✡🙏

2023-09-28 14:40 UTC, SergeyGalanin approved these changes
nice goose!

2023-09-29 12:57 UTC, NogameNo-life requested changes

2023-09-29 12:57 UTC, NogameNo-life commented on README.md
> +|8 |Яковчик Денис|[ElGansoDorado](https://github.com/ElGansoDorado)|200115|:white_check_mark:||||||||||
Надо еще отметить task_01.

2023-10-10 08:59 UTC, merged